CLASS zcl_lab_29_organization_9387 DEFINITION ABSTRACT
  PUBLIC
* FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  METHODS get_location ABSTRACT RETURNING VALUE(rv_location) type string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_29_organization_9387 IMPLEMENTATION.
ENDCLASS.
