CLASS zcl_lab_39_budget_9387 DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS get_budget ABSTRACT RETURNING VALUE(rv_gudget) type string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_39_budget_9387 IMPLEMENTATION.
ENDCLASS.
