CLASS zcl_lab_19_lion_9387 DEFINITION INHERITING FROM zcl_lab_18_animal_9387
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  METHODS walk REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_19_lion_9387 IMPLEMENTATION.
  METHOD walk.
rv_action = 'The Lion Walks'.
  ENDMETHOD.

ENDCLASS.
