CLASS zcl_lab_40_actual_budget_9387 DEFINITION
  PUBLIC
  INHERITING FROM zcl_lab_39_budget_9387
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: get_budget REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_40_actual_budget_9387 IMPLEMENTATION.
  METHOD get_budget.
rv_gudget = '50000 usd'.
  ENDMETHOD.

ENDCLASS.
