CLASS zcx_lab_57_format_unknown_9387 DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_lab_57_format_unknown_9387 IMPLEMENTATION.
ENDCLASS.
